#主配置
server:
  context-path: /api/v1
  tomcat:
    max-connections: 1000

common:
  qqwryPath: /qqwry/qqwry.dat
  requestLimit: 2

mail:
  host: smtp.qq.com
  port: 587
  sender: test@qq.com
  password: test
  attachmentSubject: The Attachment File is Coming!
  attachmentContent: 我是一封附件邮件，我被${mail.sender}扔到了${mail.host}的${mail.port}端口，然后历经千辛万苦来到了你的面前……

sms:
  url: http://www.jc-chn.cn/smsSend.do
  userName: test
  password: test
  content: 我是一条测试短信，我被某开发者发送到了您的手机……

position:
  url: http://api.map.baidu.com/location/ip
  ak: test
  coor: test

csdn:
  userName: test
  passWord: test
  loginUrl: https://passport.csdn.net/account/login
  localDir: C:/Robot_Download

qiniu:
  ak: test
  sk: test
  bucketName: csdn-data
  outerLink: http://test.com

#引用子配置
spring:
  profiles:
    active: dev
  #默认SpringBoot出现404时不会报异常，以下两句告诉SpringBoot：出现404，抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
